### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by klokailo** [DasNasu/idleshutdown#1]
deleted

**Comment by ThatsNasu** [comment]
Well, tahnks for pointing out these issues. like i described in the plugindescription on the bukkit page, it is neccessary to be familiar with batch (because of this reasons. i hardcoded the batch for my system and don't generate it dynamically (but would be a nice thought for the future)). the pointout that "start" is a lil bit other in windows 10 now is nice to know. thank you on this point, i'll change that in a couple of days. maybe i'll add some kind of scan for the used os, or i offer different versions of this plugin for different os types. your idea to add a bash version is nice, but i'm not familiar with it, since i've never used linux servers. i'm hosting everything i use like a fileserver, the minecraft server etc from home and bc of that windows was easier for my lazy person to work with. if you are familiar with bash, i would appreciate your help c:

**Comment by klokailo** [comment]
`#!/bin/sh
cd /path/to/minecraft/server/folder
java -Xmx6G -Xms2G -jar minecraft-jar.jar nogui
currenttime=dt=$(date '+%d/%m/%Y %H:%M:%S');
archivename="Backup-$currenttime"
cp -r /path/to/minecraft/server/folder /path/to/minecraft/server/backups/$archivename`
This is basically what the start script would look like in bash.
